## Traefik Configuration
## This file contains the global Traefik configuration

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry Points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Enable API and Dashboard
api:
  dashboard: true
  insecure: true

# Configure providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: colourstream_colourstream-network

# Configure certificate resolver
certificatesResolvers:
  myresolver:
    acme:
      email: admin@johnrogerscolour.co.uk
      storage: /acme.json
      httpChallenge:
        entryPoint: web

# Log configuration
log:
  level: DEBUG

# Access logs
accessLog: {} 