tls:
  certificates:
    - certFile: "/ssl/live/live.colourstream.johnrogerscolour.co.uk/cert.pem"
      keyFile: "/ssl/live/live.colourstream.johnrogerscolour.co.uk/privkey.pem"
      stores:
        - default
